spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${POSTGRESQL_PORT}/${POSTGRES_USER_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cloud:
    function:
      definition: userServiceLog
    stream:
      default-binder: UserKafka
      binders:
        UserKafka:
          type: kafka
          environment.spring.cloud.stream.kafka.binder:
            brokers: ${KAFKA_BOOTSTRAP_SERVERS}
      bindings:
        userServiceLog-out-0:
          destination: user-service-log
          content-type: application/json
        userServiceLog-in-0:
          destination: user-service-log
          content-type: application/json
          group: user-service-group
          consumer:
            batch-mode: true
            batch-size: 10
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

kafka-producer:
  topics:
    user-service-log: userServiceLog-out-0